// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evermint/vauth/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryProvedAccountOwnershipByAddressRequest is the request type for the Query/ProvedAccountOwnershipByAddress RPC method.
type QueryProvedAccountOwnershipByAddressRequest struct {
	// address is the address query for
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryProvedAccountOwnershipByAddressRequest) Reset() {
	*m = QueryProvedAccountOwnershipByAddressRequest{}
}
func (m *QueryProvedAccountOwnershipByAddressRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryProvedAccountOwnershipByAddressRequest) ProtoMessage() {}
func (*QueryProvedAccountOwnershipByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_466659dc6fde2434, []int{0}
}
func (m *QueryProvedAccountOwnershipByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProvedAccountOwnershipByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProvedAccountOwnershipByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProvedAccountOwnershipByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProvedAccountOwnershipByAddressRequest.Merge(m, src)
}
func (m *QueryProvedAccountOwnershipByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProvedAccountOwnershipByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProvedAccountOwnershipByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProvedAccountOwnershipByAddressRequest proto.InternalMessageInfo

func (m *QueryProvedAccountOwnershipByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryProvedAccountOwnershipByAddressResponse is the response type for the Query/ProvedAccountOwnershipByAddress RPC method.
type QueryProvedAccountOwnershipByAddressResponse struct {
	// proof is the proved account ownership
	Proof ProvedAccountOwnership `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof"`
}

func (m *QueryProvedAccountOwnershipByAddressResponse) Reset() {
	*m = QueryProvedAccountOwnershipByAddressResponse{}
}
func (m *QueryProvedAccountOwnershipByAddressResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryProvedAccountOwnershipByAddressResponse) ProtoMessage() {}
func (*QueryProvedAccountOwnershipByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_466659dc6fde2434, []int{1}
}
func (m *QueryProvedAccountOwnershipByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProvedAccountOwnershipByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProvedAccountOwnershipByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProvedAccountOwnershipByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProvedAccountOwnershipByAddressResponse.Merge(m, src)
}
func (m *QueryProvedAccountOwnershipByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProvedAccountOwnershipByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProvedAccountOwnershipByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProvedAccountOwnershipByAddressResponse proto.InternalMessageInfo

func (m *QueryProvedAccountOwnershipByAddressResponse) GetProof() ProvedAccountOwnership {
	if m != nil {
		return m.Proof
	}
	return ProvedAccountOwnership{}
}

func init() {
	proto.RegisterType((*QueryProvedAccountOwnershipByAddressRequest)(nil), "evermint.vauth.v1.QueryProvedAccountOwnershipByAddressRequest")
	proto.RegisterType((*QueryProvedAccountOwnershipByAddressResponse)(nil), "evermint.vauth.v1.QueryProvedAccountOwnershipByAddressResponse")
}

func init() { proto.RegisterFile("evermint/vauth/v1/query.proto", fileDescriptor_466659dc6fde2434) }

var fileDescriptor_466659dc6fde2434 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x1b, 0x71, 0x8a, 0xf1, 0x64, 0xf1, 0x30, 0x86, 0x76, 0xb2, 0x93, 0xa2, 0x36, 0x6c,
	0x82, 0x78, 0x9a, 0x6c, 0x30, 0x76, 0x54, 0x77, 0xf4, 0x52, 0xb2, 0x2e, 0x76, 0x05, 0x97, 0x37,
	0x4b, 0xd2, 0x6a, 0xaf, 0x7e, 0x02, 0xc1, 0x2f, 0xb5, 0xe3, 0xc0, 0x8b, 0x27, 0x91, 0xce, 0xa3,
	0x1f, 0x42, 0x96, 0x6c, 0x20, 0x6c, 0xe2, 0x9f, 0x5b, 0x9b, 0x27, 0xef, 0xef, 0xc7, 0x93, 0x17,
	0xef, 0xb2, 0x94, 0xc9, 0x41, 0xcc, 0x35, 0x49, 0x69, 0xa2, 0xfb, 0x24, 0xad, 0x92, 0x61, 0xc2,
	0x64, 0xe6, 0x0b, 0x09, 0x1a, 0xdc, 0xad, 0x79, 0xec, 0x9b, 0xd8, 0x4f, 0xab, 0xa5, 0xed, 0x08,
	0x22, 0x30, 0x29, 0x99, 0x7e, 0xd9, 0x8b, 0xa5, 0x9d, 0x08, 0x20, 0xba, 0x65, 0x84, 0x8a, 0x98,
	0x50, 0xce, 0x41, 0x53, 0x1d, 0x03, 0x57, 0xb3, 0x74, 0x89, 0xc5, 0xf2, 0x4c, 0x5c, 0x69, 0xe3,
	0xc3, 0xab, 0xa9, 0xf4, 0x52, 0x42, 0xca, 0x7a, 0x8d, 0x30, 0x84, 0x84, 0xeb, 0x8b, 0x3b, 0xce,
	0xa4, 0xea, 0xc7, 0xa2, 0x99, 0x35, 0x7a, 0x3d, 0xc9, 0x94, 0xea, 0xb0, 0x61, 0xc2, 0x94, 0x76,
	0x8b, 0x78, 0x9d, 0xda, 0x93, 0x22, 0xda, 0x43, 0xfb, 0x1b, 0x9d, 0xf9, 0x6f, 0x25, 0xc1, 0x47,
	0xbf, 0x03, 0x29, 0x01, 0x5c, 0x31, 0xb7, 0x85, 0x0b, 0x42, 0x02, 0xdc, 0x18, 0xce, 0x66, 0xed,
	0xc0, 0x5f, 0xa8, 0xeb, 0x7f, 0x83, 0x5a, 0x1d, 0xbd, 0x96, 0x9d, 0x8e, 0x9d, 0xae, 0x7d, 0x20,
	0x5c, 0x30, 0x5e, 0x37, 0x47, 0xb8, 0xfc, 0x83, 0xdc, 0xad, 0x2f, 0xb1, 0xfc, 0xa1, 0x7e, 0xe9,
	0xfc, 0xdf, 0xf3, 0xb6, 0x75, 0xa5, 0xfe, 0xf0, 0xfc, 0xfe, 0xb4, 0x72, 0xe6, 0x9e, 0x92, 0xc5,
	0xb5, 0x08, 0xc3, 0x08, 0xa8, 0x85, 0x04, 0x30, 0xa7, 0x04, 0xdd, 0x2c, 0x98, 0xbd, 0x72, 0xb3,
	0x3d, 0xca, 0x3d, 0x34, 0xce, 0x3d, 0xf4, 0x96, 0x7b, 0xe8, 0x71, 0xe2, 0x39, 0xe3, 0x89, 0xe7,
	0xbc, 0x4c, 0x3c, 0xe7, 0xfa, 0x38, 0x8a, 0x75, 0x3f, 0xe9, 0xfa, 0x21, 0x0c, 0x48, 0x4b, 0x85,
	0x94, 0x37, 0x5b, 0x5f, 0x1c, 0xd5, 0x1a, 0xb9, 0x9f, 0x99, 0x74, 0x26, 0x98, 0xea, 0xae, 0x99,
	0xf5, 0x9f, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x96, 0x02, 0xfb, 0x85, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Address retrieves the proof by account address
	ProvedAccountOwnershipByAddress(ctx context.Context, in *QueryProvedAccountOwnershipByAddressRequest, opts ...grpc.CallOption) (*QueryProvedAccountOwnershipByAddressResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ProvedAccountOwnershipByAddress(ctx context.Context, in *QueryProvedAccountOwnershipByAddressRequest, opts ...grpc.CallOption) (*QueryProvedAccountOwnershipByAddressResponse, error) {
	out := new(QueryProvedAccountOwnershipByAddressResponse)
	err := c.cc.Invoke(ctx, "/evermint.vauth.v1.Query/ProvedAccountOwnershipByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Address retrieves the proof by account address
	ProvedAccountOwnershipByAddress(context.Context, *QueryProvedAccountOwnershipByAddressRequest) (*QueryProvedAccountOwnershipByAddressResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ProvedAccountOwnershipByAddress(ctx context.Context, req *QueryProvedAccountOwnershipByAddressRequest) (*QueryProvedAccountOwnershipByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvedAccountOwnershipByAddress not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ProvedAccountOwnershipByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProvedAccountOwnershipByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProvedAccountOwnershipByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evermint.vauth.v1.Query/ProvedAccountOwnershipByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProvedAccountOwnershipByAddress(ctx, req.(*QueryProvedAccountOwnershipByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evermint.vauth.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProvedAccountOwnershipByAddress",
			Handler:    _Query_ProvedAccountOwnershipByAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evermint/vauth/v1/query.proto",
}

func (m *QueryProvedAccountOwnershipByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProvedAccountOwnershipByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProvedAccountOwnershipByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProvedAccountOwnershipByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProvedAccountOwnershipByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProvedAccountOwnershipByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryProvedAccountOwnershipByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryProvedAccountOwnershipByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Proof.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryProvedAccountOwnershipByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProvedAccountOwnershipByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProvedAccountOwnershipByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProvedAccountOwnershipByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProvedAccountOwnershipByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProvedAccountOwnershipByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
