// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evermint/vauth/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitProofExternalOwnedAccount defines a Msg to submit EOA proof
type MsgSubmitProofExternalOwnedAccount struct {
	// submitter is the cosmos bech32 address of the account who submitted the proof
	Submitter string `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// account is the cosmos bech32 address that submit proof for
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	// signature is the Ethereum signed message, used to proof that the account is EOA
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *MsgSubmitProofExternalOwnedAccount) Reset()         { *m = MsgSubmitProofExternalOwnedAccount{} }
func (m *MsgSubmitProofExternalOwnedAccount) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitProofExternalOwnedAccount) ProtoMessage()    {}
func (*MsgSubmitProofExternalOwnedAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_74b474a4acdc4171, []int{0}
}
func (m *MsgSubmitProofExternalOwnedAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitProofExternalOwnedAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitProofExternalOwnedAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitProofExternalOwnedAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitProofExternalOwnedAccount.Merge(m, src)
}
func (m *MsgSubmitProofExternalOwnedAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitProofExternalOwnedAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitProofExternalOwnedAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitProofExternalOwnedAccount proto.InternalMessageInfo

func (m *MsgSubmitProofExternalOwnedAccount) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgSubmitProofExternalOwnedAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MsgSubmitProofExternalOwnedAccount) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

// MsgSubmitProofExternalOwnedAccountResponse returns no fields
type MsgSubmitProofExternalOwnedAccountResponse struct {
}

func (m *MsgSubmitProofExternalOwnedAccountResponse) Reset() {
	*m = MsgSubmitProofExternalOwnedAccountResponse{}
}
func (m *MsgSubmitProofExternalOwnedAccountResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgSubmitProofExternalOwnedAccountResponse) ProtoMessage() {}
func (*MsgSubmitProofExternalOwnedAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74b474a4acdc4171, []int{1}
}
func (m *MsgSubmitProofExternalOwnedAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitProofExternalOwnedAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitProofExternalOwnedAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitProofExternalOwnedAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitProofExternalOwnedAccountResponse.Merge(m, src)
}
func (m *MsgSubmitProofExternalOwnedAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitProofExternalOwnedAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitProofExternalOwnedAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitProofExternalOwnedAccountResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSubmitProofExternalOwnedAccount)(nil), "evermint.vauth.v1.MsgSubmitProofExternalOwnedAccount")
	proto.RegisterType((*MsgSubmitProofExternalOwnedAccountResponse)(nil), "evermint.vauth.v1.MsgSubmitProofExternalOwnedAccountResponse")
}

func init() { proto.RegisterFile("evermint/vauth/v1/tx.proto", fileDescriptor_74b474a4acdc4171) }

var fileDescriptor_74b474a4acdc4171 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0x7b, 0x2d, 0x28, 0xcd, 0x20, 0x18, 0x04, 0x63, 0x28, 0x51, 0x32, 0x49, 0xd1, 0x1c,
	0xad, 0x38, 0xa8, 0x38, 0xb4, 0x50, 0x9c, 0x8a, 0x52, 0x37, 0x97, 0x70, 0x8d, 0xd7, 0x6b, 0xa0,
	0xb9, 0x17, 0x72, 0x97, 0x58, 0xd7, 0x8e, 0x4e, 0x82, 0x5f, 0xc4, 0x8f, 0xe1, 0x58, 0x70, 0x11,
	0x27, 0x49, 0x05, 0xbf, 0x86, 0x24, 0x97, 0x50, 0x41, 0xa1, 0xe0, 0x76, 0xef, 0xfd, 0xde, 0xfb,
	0xbf, 0x77, 0xef, 0xaf, 0x99, 0x34, 0xa1, 0x51, 0xe0, 0x73, 0x89, 0x13, 0x12, 0xcb, 0x31, 0x4e,
	0x5a, 0x58, 0x4e, 0x9d, 0x30, 0x02, 0x09, 0xfa, 0x66, 0xc9, 0x9c, 0x9c, 0x39, 0x49, 0xcb, 0xdc,
	0x62, 0xc0, 0x20, 0xa7, 0x38, 0x7b, 0xa9, 0x42, 0xb3, 0xc1, 0x00, 0xd8, 0x84, 0x62, 0x12, 0xfa,
	0x98, 0x70, 0x0e, 0x92, 0x48, 0x1f, 0xb8, 0x28, 0xe8, 0xb6, 0x07, 0x22, 0x00, 0x81, 0x03, 0xc1,
	0x32, 0xf9, 0x40, 0xb0, 0x02, 0xec, 0x28, 0xe0, 0x2a, 0x3d, 0x15, 0x28, 0x64, 0x3f, 0x20, 0xcd,
	0xee, 0x0b, 0x76, 0x1d, 0x0f, 0x03, 0x5f, 0x5e, 0x45, 0x00, 0xa3, 0xde, 0x54, 0xd2, 0x88, 0x93,
	0xc9, 0xe5, 0x1d, 0xa7, 0xb7, 0x1d, 0xcf, 0x83, 0x98, 0x4b, 0xbd, 0xa1, 0xd5, 0x45, 0x5e, 0x22,
	0x69, 0x64, 0xa0, 0x3d, 0xb4, 0x5f, 0x1f, 0x2c, 0x13, 0xba, 0xa1, 0xad, 0x13, 0x55, 0x68, 0x54,
	0x73, 0x56, 0x86, 0x79, 0x9f, 0xcf, 0x38, 0x91, 0x71, 0x44, 0x8d, 0x5a, 0xd1, 0x57, 0x26, 0x4e,
	0x37, 0x66, 0x5f, 0xcf, 0xcd, 0xa5, 0x8e, 0x7d, 0xa0, 0x35, 0x57, 0xef, 0x32, 0xa0, 0x22, 0x04,
	0x2e, 0x68, 0x3b, 0x45, 0x5a, 0xad, 0x2f, 0x98, 0xfe, 0x8e, 0xb4, 0xdd, 0x55, 0xfb, 0x1f, 0x3b,
	0xbf, 0x4e, 0xec, 0xac, 0x1e, 0x65, 0x9e, 0xff, 0xab, 0xad, 0xdc, 0xd0, 0xee, 0xcc, 0x5e, 0x3f,
	0x9f, 0xaa, 0x67, 0xfa, 0x09, 0xfe, 0xcb, 0x7c, 0xac, 0x3e, 0x9e, 0xb9, 0x02, 0x23, 0x97, 0x16,
	0x42, 0x2e, 0x64, 0x4a, 0x6e, 0x71, 0xc0, 0xee, 0xc5, 0x4b, 0x6a, 0xa1, 0x79, 0x6a, 0xa1, 0x8f,
	0xd4, 0x42, 0x8f, 0x0b, 0xab, 0x32, 0x5f, 0x58, 0x95, 0xb7, 0x85, 0x55, 0xb9, 0x39, 0x64, 0xbe,
	0x1c, 0xc7, 0x43, 0xc7, 0x83, 0x00, 0xf7, 0x84, 0x47, 0x78, 0xb7, 0xf7, 0x63, 0x4c, 0xab, 0x8d,
	0xa7, 0xc5, 0x30, 0x79, 0x1f, 0x52, 0x31, 0x5c, 0xcb, 0xfd, 0x3e, 0xfa, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0xc1, 0xe7, 0x51, 0x55, 0x88, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SubmitProofExternalOwnedAccount submit proof that an account is external owned account (EOA)
	SubmitProofExternalOwnedAccount(ctx context.Context, in *MsgSubmitProofExternalOwnedAccount, opts ...grpc.CallOption) (*MsgSubmitProofExternalOwnedAccountResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitProofExternalOwnedAccount(ctx context.Context, in *MsgSubmitProofExternalOwnedAccount, opts ...grpc.CallOption) (*MsgSubmitProofExternalOwnedAccountResponse, error) {
	out := new(MsgSubmitProofExternalOwnedAccountResponse)
	err := c.cc.Invoke(ctx, "/evermint.vauth.v1.Msg/SubmitProofExternalOwnedAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SubmitProofExternalOwnedAccount submit proof that an account is external owned account (EOA)
	SubmitProofExternalOwnedAccount(context.Context, *MsgSubmitProofExternalOwnedAccount) (*MsgSubmitProofExternalOwnedAccountResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitProofExternalOwnedAccount(ctx context.Context, req *MsgSubmitProofExternalOwnedAccount) (*MsgSubmitProofExternalOwnedAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitProofExternalOwnedAccount not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitProofExternalOwnedAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitProofExternalOwnedAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitProofExternalOwnedAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evermint.vauth.v1.Msg/SubmitProofExternalOwnedAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitProofExternalOwnedAccount(ctx, req.(*MsgSubmitProofExternalOwnedAccount))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evermint.vauth.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitProofExternalOwnedAccount",
			Handler:    _Msg_SubmitProofExternalOwnedAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evermint/vauth/v1/tx.proto",
}

func (m *MsgSubmitProofExternalOwnedAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitProofExternalOwnedAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitProofExternalOwnedAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitProofExternalOwnedAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitProofExternalOwnedAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitProofExternalOwnedAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitProofExternalOwnedAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitProofExternalOwnedAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitProofExternalOwnedAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitProofExternalOwnedAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitProofExternalOwnedAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitProofExternalOwnedAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitProofExternalOwnedAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitProofExternalOwnedAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
