// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: evermint/vauth/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitProveAccountOwnership defines a Msg to submit account ownership proof
type MsgSubmitProveAccountOwnership struct {
	// submitter is the cosmos bech32 address of the account who submitted the proof
	Submitter string `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	// address is the cosmos bech32 address that submit proof for
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// signature is the Ethereum signed message
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *MsgSubmitProveAccountOwnership) Reset()         { *m = MsgSubmitProveAccountOwnership{} }
func (m *MsgSubmitProveAccountOwnership) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitProveAccountOwnership) ProtoMessage()    {}
func (*MsgSubmitProveAccountOwnership) Descriptor() ([]byte, []int) {
	return fileDescriptor_74b474a4acdc4171, []int{0}
}
func (m *MsgSubmitProveAccountOwnership) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitProveAccountOwnership) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitProveAccountOwnership.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitProveAccountOwnership) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitProveAccountOwnership.Merge(m, src)
}
func (m *MsgSubmitProveAccountOwnership) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitProveAccountOwnership) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitProveAccountOwnership.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitProveAccountOwnership proto.InternalMessageInfo

func (m *MsgSubmitProveAccountOwnership) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgSubmitProveAccountOwnership) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgSubmitProveAccountOwnership) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

// MsgSubmitProveAccountOwnershipResponse returns no fields
type MsgSubmitProveAccountOwnershipResponse struct {
}

func (m *MsgSubmitProveAccountOwnershipResponse) Reset() {
	*m = MsgSubmitProveAccountOwnershipResponse{}
}
func (m *MsgSubmitProveAccountOwnershipResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitProveAccountOwnershipResponse) ProtoMessage()    {}
func (*MsgSubmitProveAccountOwnershipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_74b474a4acdc4171, []int{1}
}
func (m *MsgSubmitProveAccountOwnershipResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitProveAccountOwnershipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitProveAccountOwnershipResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitProveAccountOwnershipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitProveAccountOwnershipResponse.Merge(m, src)
}
func (m *MsgSubmitProveAccountOwnershipResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitProveAccountOwnershipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitProveAccountOwnershipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitProveAccountOwnershipResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSubmitProveAccountOwnership)(nil), "evermint.vauth.v1.MsgSubmitProveAccountOwnership")
	proto.RegisterType((*MsgSubmitProveAccountOwnershipResponse)(nil), "evermint.vauth.v1.MsgSubmitProveAccountOwnershipResponse")
}

func init() { proto.RegisterFile("evermint/vauth/v1/tx.proto", fileDescriptor_74b474a4acdc4171) }

var fileDescriptor_74b474a4acdc4171 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0x7b, 0x2d, 0x28, 0xcd, 0x20, 0x18, 0x04, 0x63, 0x2c, 0x41, 0x3a, 0x48, 0x11, 0xcc,
	0x91, 0x2a, 0x82, 0xe2, 0x62, 0xa1, 0x38, 0x15, 0xa5, 0x6e, 0x2e, 0xe5, 0x9a, 0x1e, 0xd7, 0x80,
	0xb9, 0x17, 0xf2, 0x2e, 0xb1, 0xae, 0x1d, 0x9c, 0x05, 0xbf, 0x88, 0x1f, 0x43, 0xb7, 0x8a, 0x8b,
	0xa3, 0xb4, 0x82, 0x5f, 0x43, 0x9a, 0x4b, 0xa8, 0xa0, 0x14, 0xdc, 0xee, 0xbd, 0xdf, 0xbd, 0xff,
	0xfb, 0xdf, 0xfd, 0x0d, 0x9b, 0xa7, 0x3c, 0x0e, 0x03, 0xa9, 0x68, 0xca, 0x12, 0x35, 0xa4, 0xa9,
	0x47, 0xd5, 0xc8, 0x8d, 0x62, 0x50, 0x60, 0xae, 0x17, 0xcc, 0xcd, 0x98, 0x9b, 0x7a, 0xf6, 0x86,
	0x00, 0x01, 0x19, 0xa5, 0xf3, 0x93, 0xbe, 0x68, 0xd7, 0x04, 0x80, 0xb8, 0xe1, 0x94, 0x45, 0x01,
	0x65, 0x52, 0x82, 0x62, 0x2a, 0x00, 0x89, 0x39, 0xdd, 0xf4, 0x01, 0x43, 0x40, 0x1a, 0xa2, 0x98,
	0xcb, 0x87, 0x28, 0x72, 0xb0, 0xa5, 0x41, 0x4f, 0xeb, 0xe9, 0x42, 0xa3, 0xfa, 0x3d, 0x31, 0x9c,
	0x0e, 0x8a, 0xab, 0xa4, 0x1f, 0x06, 0xea, 0x32, 0x86, 0x94, 0x9f, 0xf9, 0x3e, 0x24, 0x52, 0x5d,
	0xdc, 0x4a, 0x1e, 0xe3, 0x30, 0x88, 0xcc, 0x9a, 0x51, 0xc5, 0x0c, 0x2b, 0x1e, 0x5b, 0x64, 0x87,
	0x34, 0xaa, 0xdd, 0x45, 0xc3, 0xb4, 0x8c, 0x55, 0x36, 0x18, 0xc4, 0x1c, 0xd1, 0x2a, 0x67, 0xac,
	0x28, 0xb3, 0xb9, 0x40, 0x48, 0xa6, 0x92, 0x98, 0x5b, 0x95, 0x7c, 0xae, 0x68, 0x9c, 0xac, 0x8d,
	0xbf, 0x9e, 0xf6, 0x16, 0x3a, 0xf5, 0x86, 0xb1, 0xbb, 0xdc, 0x47, 0x97, 0x63, 0x04, 0x12, 0x79,
	0xf3, 0x95, 0x18, 0x95, 0x0e, 0x0a, 0xf3, 0x85, 0x18, 0xdb, 0xcb, 0x7c, 0x7b, 0xee, 0xaf, 0x6f,
	0x75, 0x97, 0xaf, 0xb0, 0x8f, 0xff, 0x3d, 0x52, 0xb8, 0xaa, 0x9f, 0x8e, 0xdf, 0x3e, 0x1f, 0xcb,
	0x47, 0xe6, 0x21, 0xfd, 0x2b, 0x68, 0xaa, 0x1f, 0x3a, 0x4f, 0x20, 0xe5, 0x3d, 0xa6, 0x45, 0x7a,
	0x50, 0xa8, 0xb4, 0xce, 0x9f, 0xa7, 0x0e, 0x99, 0x4c, 0x1d, 0xf2, 0x31, 0x75, 0xc8, 0xc3, 0xcc,
	0x29, 0x4d, 0x66, 0x4e, 0xe9, 0x7d, 0xe6, 0x94, 0xae, 0xf7, 0x45, 0xa0, 0x86, 0x49, 0xdf, 0xf5,
	0x21, 0xa4, 0x6d, 0xf4, 0x99, 0x6c, 0xb5, 0x7f, 0x6c, 0xf0, 0x9a, 0x74, 0x94, 0xef, 0x51, 0x77,
	0x11, 0xc7, 0xfe, 0x4a, 0x16, 0xeb, 0xc1, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x23, 0x94, 0x87,
	0xde, 0x6f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SubmitProveAccountOwnership submit account ownership proof and persist to store.
	SubmitProveAccountOwnership(ctx context.Context, in *MsgSubmitProveAccountOwnership, opts ...grpc.CallOption) (*MsgSubmitProveAccountOwnershipResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitProveAccountOwnership(ctx context.Context, in *MsgSubmitProveAccountOwnership, opts ...grpc.CallOption) (*MsgSubmitProveAccountOwnershipResponse, error) {
	out := new(MsgSubmitProveAccountOwnershipResponse)
	err := c.cc.Invoke(ctx, "/evermint.vauth.v1.Msg/SubmitProveAccountOwnership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SubmitProveAccountOwnership submit account ownership proof and persist to store.
	SubmitProveAccountOwnership(context.Context, *MsgSubmitProveAccountOwnership) (*MsgSubmitProveAccountOwnershipResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitProveAccountOwnership(ctx context.Context, req *MsgSubmitProveAccountOwnership) (*MsgSubmitProveAccountOwnershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitProveAccountOwnership not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitProveAccountOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitProveAccountOwnership)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitProveAccountOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evermint.vauth.v1.Msg/SubmitProveAccountOwnership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitProveAccountOwnership(ctx, req.(*MsgSubmitProveAccountOwnership))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evermint.vauth.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitProveAccountOwnership",
			Handler:    _Msg_SubmitProveAccountOwnership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evermint/vauth/v1/tx.proto",
}

func (m *MsgSubmitProveAccountOwnership) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitProveAccountOwnership) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitProveAccountOwnership) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitProveAccountOwnershipResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitProveAccountOwnershipResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitProveAccountOwnershipResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitProveAccountOwnership) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitProveAccountOwnershipResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitProveAccountOwnership) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitProveAccountOwnership: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitProveAccountOwnership: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitProveAccountOwnershipResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitProveAccountOwnershipResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitProveAccountOwnershipResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
