// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: evermint/cpc/v1/query.proto

package cpcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_CustomPrecompiledContracts_FullMethodName            = "/evermint.cpc.v1.Query/CustomPrecompiledContracts"
	Query_CustomPrecompiledContract_FullMethodName             = "/evermint.cpc.v1.Query/CustomPrecompiledContract"
	Query_Erc20CustomPrecompiledContractByDenom_FullMethodName = "/evermint.cpc.v1.Query/Erc20CustomPrecompiledContractByDenom"
	Query_Params_FullMethodName                                = "/evermint.cpc.v1.Query/Params"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// CustomPrecompiledContracts queries the list of deployed custom precompiled contracts.
	CustomPrecompiledContracts(ctx context.Context, in *QueryCustomPrecompiledContractsRequest, opts ...grpc.CallOption) (*QueryCustomPrecompiledContractsResponse, error)
	// CustomPrecompiledContract queries the list of deployed custom precompiled contract.
	CustomPrecompiledContract(ctx context.Context, in *QueryCustomPrecompiledContractRequest, opts ...grpc.CallOption) (*QueryCustomPrecompiledContractResponse, error)
	// Erc20CustomPrecompiledContractByDenom queries the list of deployed custom precompiled contract by denom.
	Erc20CustomPrecompiledContractByDenom(ctx context.Context, in *QueryErc20CustomPrecompiledContractByDenomRequest, opts ...grpc.CallOption) (*QueryErc20CustomPrecompiledContractByDenomResponse, error)
	// Params queries the parameters of x/cpc module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CustomPrecompiledContracts(ctx context.Context, in *QueryCustomPrecompiledContractsRequest, opts ...grpc.CallOption) (*QueryCustomPrecompiledContractsResponse, error) {
	out := new(QueryCustomPrecompiledContractsResponse)
	err := c.cc.Invoke(ctx, Query_CustomPrecompiledContracts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CustomPrecompiledContract(ctx context.Context, in *QueryCustomPrecompiledContractRequest, opts ...grpc.CallOption) (*QueryCustomPrecompiledContractResponse, error) {
	out := new(QueryCustomPrecompiledContractResponse)
	err := c.cc.Invoke(ctx, Query_CustomPrecompiledContract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Erc20CustomPrecompiledContractByDenom(ctx context.Context, in *QueryErc20CustomPrecompiledContractByDenomRequest, opts ...grpc.CallOption) (*QueryErc20CustomPrecompiledContractByDenomResponse, error) {
	out := new(QueryErc20CustomPrecompiledContractByDenomResponse)
	err := c.cc.Invoke(ctx, Query_Erc20CustomPrecompiledContractByDenom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// CustomPrecompiledContracts queries the list of deployed custom precompiled contracts.
	CustomPrecompiledContracts(context.Context, *QueryCustomPrecompiledContractsRequest) (*QueryCustomPrecompiledContractsResponse, error)
	// CustomPrecompiledContract queries the list of deployed custom precompiled contract.
	CustomPrecompiledContract(context.Context, *QueryCustomPrecompiledContractRequest) (*QueryCustomPrecompiledContractResponse, error)
	// Erc20CustomPrecompiledContractByDenom queries the list of deployed custom precompiled contract by denom.
	Erc20CustomPrecompiledContractByDenom(context.Context, *QueryErc20CustomPrecompiledContractByDenomRequest) (*QueryErc20CustomPrecompiledContractByDenomResponse, error)
	// Params queries the parameters of x/cpc module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) CustomPrecompiledContracts(context.Context, *QueryCustomPrecompiledContractsRequest) (*QueryCustomPrecompiledContractsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomPrecompiledContracts not implemented")
}
func (UnimplementedQueryServer) CustomPrecompiledContract(context.Context, *QueryCustomPrecompiledContractRequest) (*QueryCustomPrecompiledContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomPrecompiledContract not implemented")
}
func (UnimplementedQueryServer) Erc20CustomPrecompiledContractByDenom(context.Context, *QueryErc20CustomPrecompiledContractByDenomRequest) (*QueryErc20CustomPrecompiledContractByDenomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Erc20CustomPrecompiledContractByDenom not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_CustomPrecompiledContracts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCustomPrecompiledContractsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CustomPrecompiledContracts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CustomPrecompiledContracts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CustomPrecompiledContracts(ctx, req.(*QueryCustomPrecompiledContractsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CustomPrecompiledContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCustomPrecompiledContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CustomPrecompiledContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CustomPrecompiledContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CustomPrecompiledContract(ctx, req.(*QueryCustomPrecompiledContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Erc20CustomPrecompiledContractByDenom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryErc20CustomPrecompiledContractByDenomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Erc20CustomPrecompiledContractByDenom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Erc20CustomPrecompiledContractByDenom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Erc20CustomPrecompiledContractByDenom(ctx, req.(*QueryErc20CustomPrecompiledContractByDenomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evermint.cpc.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CustomPrecompiledContracts",
			Handler:    _Query_CustomPrecompiledContracts_Handler,
		},
		{
			MethodName: "CustomPrecompiledContract",
			Handler:    _Query_CustomPrecompiledContract_Handler,
		},
		{
			MethodName: "Erc20CustomPrecompiledContractByDenom",
			Handler:    _Query_Erc20CustomPrecompiledContractByDenom_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evermint/cpc/v1/query.proto",
}
